name: CI

on:
  pull_request:
    branches:
      - "it*"
      - "main"

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Clean install node modules
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Vitest in integration tests
        run: npx vitest tests/*/integration/*.test.ts
